name: Publish to NPM

on:
  push:
    branches: [main]
    paths:
      - 'packages/*/package.json'
      - 'packages/*/src/**'
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to publish (e.g., countries, timezones)'
        required: true
        type: choice
        options:
          - countries
          - timezones
          - all

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.0
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build packages
        run: pnpm build
      
      - name: Run tests
        run: pnpm test
      
      - name: Check if countries version already published
        id: check-countries-version
        run: |
          PACKAGE_NAME="@countrystatecity/countries"
          PACKAGE_VERSION=$(node -p "require('./packages/countries/package.json').version")
          
          echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
          
          if npm view "$PACKAGE_NAME@$PACKAGE_VERSION" version 2>/dev/null; then
            echo "published=true" >> $GITHUB_OUTPUT
            echo "Countries version $PACKAGE_VERSION already published"
          else
            echo "published=false" >> $GITHUB_OUTPUT
            echo "Countries version $PACKAGE_VERSION not yet published"
          fi
      
      - name: Check if timezones version already published
        id: check-timezones-version
        run: |
          PACKAGE_NAME="@countrystatecity/timezones"
          PACKAGE_VERSION=$(node -p "require('./packages/timezones/package.json').version")
          
          echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
          
          if npm view "$PACKAGE_NAME@$PACKAGE_VERSION" version 2>/dev/null; then
            echo "published=true" >> $GITHUB_OUTPUT
            echo "Timezones version $PACKAGE_VERSION already published"
          else
            echo "published=false" >> $GITHUB_OUTPUT
            echo "Timezones version $PACKAGE_VERSION not yet published"
          fi
      
      - name: Publish @countrystatecity/countries
        if: |
          steps.check-countries-version.outputs.published == 'false' && 
          (github.event.inputs.package == 'countries' || github.event.inputs.package == 'all' || github.event_name == 'push')
        run: |
          cd packages/countries
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Publish @countrystatecity/timezones
        if: |
          steps.check-timezones-version.outputs.published == 'false' && 
          (github.event.inputs.package == 'timezones' || github.event.inputs.package == 'all' || github.event_name == 'push')
        run: |
          cd packages/timezones
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Create GitHub Release for countries
        if: |
          steps.check-countries-version.outputs.published == 'false' && 
          (github.event.inputs.package == 'countries' || github.event.inputs.package == 'all' || github.event_name == 'push')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: countries-v${{ steps.check-countries-version.outputs.version }}
          name: Countries v${{ steps.check-countries-version.outputs.version }}
          body: |
            ## @countrystatecity/countries v${{ steps.check-countries-version.outputs.version }}
            
            Published to NPM: https://www.npmjs.com/package/@countrystatecity/countries
            
            ### Installation
            ```bash
            npm install @countrystatecity/countries
            ```
            
            See the [README](https://github.com/dr5hn/countrystatecity/blob/main/packages/countries/README.md) for usage instructions.
          draft: false
          prerelease: false
      
      - name: Create GitHub Release for timezones
        if: |
          steps.check-timezones-version.outputs.published == 'false' && 
          (github.event.inputs.package == 'timezones' || github.event.inputs.package == 'all' || github.event_name == 'push')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: timezones-v${{ steps.check-timezones-version.outputs.version }}
          name: Timezones v${{ steps.check-timezones-version.outputs.version }}
          body: |
            ## @countrystatecity/timezones v${{ steps.check-timezones-version.outputs.version }}
            
            Published to NPM: https://www.npmjs.com/package/@countrystatecity/timezones
            
            ### Installation
            ```bash
            npm install @countrystatecity/timezones
            ```
            
            See the [README](https://github.com/dr5hn/countrystatecity/blob/main/packages/timezones/README.md) for usage instructions.
          draft: false
          prerelease: false
